[15기 김순태] Add: 추가 API 구현 (서비스, 상세페이지)
wecode-bootcamp-korea/15-1st-Youngchapedia-backend pull request #10
Opened 2020-12-21 16:38 UTC by kst6294

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- API 추가
		 
## 수정 사항들 자세한 내용
- Watcha / Netflix 컨텐츠 API 구현 
- 컨텐츠 상세페이지에서 사용할 API 구현 
- > Gallery (사진) / Overview (상세페이지 -> 더보기 정보) / Cast 컨텐츠 캐스팅 정보

## 기타 질문 및 특이 사항
- 최대한 for loop 가 아닌 list comprehension 으로 loop를 구현하려고 했음. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-22 13:14 UTC, lordmyshepherd requested changes

2020-12-22 13:14 UTC, lordmyshepherd commented on content/views.py
> +            ]
왜 list에 담아서 반환하나요?

2020-12-22 13:14 UTC, lordmyshepherd commented on content/views.py
> +            genres           = content.contentgenre_set.all()
아래 dictionary 안에 합쳐주세요.

2020-12-22 13:14 UTC, lordmyshepherd commented on content/views.py
> +            ]
마찬가지 입니다. 리스트로 반환하시는 이유가 있나요?

2020-12-22 13:14 UTC, lordmyshepherd commented on content/views.py
> +        ]
**services** 객체로부터 접근해서 모든 데이터를 가져올 수 있습니다.
`watcha_contents`로 조회하는 쿼리를 줄일 수 있습니다.

```suggestion
        services = ContentService.objects.get(name='watcha')
        watcha_content_list = [
            {
                'id'             : watcha_content.content.id,
                'title_korean'   : watcha_content.content.title_korean,
                'title_original' : watcha_content.content.movieoverview_set.get().title_original,
                'category'       : watcha_content.content.category.name,
                'main_image_url' : watcha_content.content.main_image_url,
            } for services.watcha_content in services
        ]
```

2020-12-22 13:14 UTC, lordmyshepherd commented on content/views.py
> +        ]
여기는 리스트에 객체가 하나 포함되네요??
왜 리스트로 반환하죠?

2020-12-22 13:14 UTC, lordmyshepherd commented on content/views.py
> +            gallery_photos     = ContentPhoto.objects.filter(content_id=content_id)
`content`로 접근해서 모든 데이터를 조회해 올 수 있습니다.
```suggestion
            content            = Content.objects.get(id=content_id)
```

2020-12-22 17:50 UTC, kst6294 commented on content/views.py
> +            ]
불필요하게 리스트에 담지 않고 바로 딕셔너리로 반환되도록 수정했습니다.

2020-12-22 17:59 UTC, kst6294 commented on content/views.py
> +            genres           = content.contentgenre_set.all()
반영했습니다

2020-12-22 18:06 UTC, kst6294 commented on content/views.py
> +            ]
이부분은 하나의 컨텐츠 안에 캐스트로 포함되는 사람의 목록이 2명 이상이기 때문에 리스트에 담아서 반환했습니다.

2020-12-22 18:31 UTC, kst6294 commented on content/views.py
> +        ]
불필요한 리스트 반환 제거하고 바로 딕셔너리로 반환되도록 수정했습니다.

2020-12-22 18:31 UTC, kst6294 commented on content/views.py
> +        ]
반영했습니다.

2020-12-22 18:34 UTC, kst6294 commented on content/views.py
> +            gallery_photos     = ContentPhoto.objects.filter(content_id=content_id)
반영했습니다.

2020-12-22 18:46 UTC, kst6294 commented on content/views.py
> +            ]
해당 피드백의 의도가 바로 반환되는 데이터가 딕셔너리가 아닌 리스트인 것 때문이신 것 같아서, 기존의 다른 코드와 같이 딕셔너리로 반환을 하되, 반복되는 cast 만 리스트에 담아서 반환하는 것으로 수정했습니다.

수정 반영 내용이 피드백의 의도와 맞을까요?

2020-12-23 02:07 UTC, lordmyshepherd requested changes

2020-12-23 02:07 UTC, lordmyshepherd commented on \
> +import json
이 파일은 뭔가요??? 지워주세요!

2020-12-23 02:07 UTC, lordmyshepherd commented on content/views.py
> +            }
👍

2020-12-23 02:07 UTC, lordmyshepherd commented on content/views.py
> +            }
이 부분은 전달이 잘 못 된 것 같아요!
```suggestion
            results = [
                {
                    'people_id'        : people.people.id,
                    'people_name'      : people.people.name,
                    'role'             : people.role_name,
                    'people_image_url' : people.people.profile_image_url,
                } for people in content.contentpeople_set.all()
            ]
```

2020-12-23 02:07 UTC, lordmyshepherd commented on content/views.py
> +        services = ContentService.objects.get(name='watcha')
변수명을 명확하게 수정해주세요! 실제로 services 변수에 담긴 객체는 Service의 instance가 아니라 ContenService 인스턴스 입니다. 지금 저만 보더라도 코드를 이해하기가 어렵습니다.
```suggestion
        content_service = ContentService.objects.get(name='watcha')
```

2020-12-23 02:07 UTC, lordmyshepherd commented on content/views.py
> +        services              = ContentService.objects.get(name='netflix')
마찬가지로 변수명을 명확하게 수정해주세요!

2020-12-23 02:07 UTC, lordmyshepherd commented on content/views.py
> +                'galleris_image'       : gallery_photo_list,
```suggestion
                'gallery_images'       : gallery_photo_list,
```

2020-12-23 02:16 UTC, kst6294 commented on content/views.py
> +        services              = ContentService.objects.get(name='netflix')
반영했습니다.

2020-12-23 02:16 UTC, kst6294 commented on content/views.py
> +                'galleris_image'       : gallery_photo_list,
반영했습니다.

2020-12-23 02:16 UTC, kst6294 commented on content/views.py
> +        services              = ContentService.objects.get(name='netflix')
반영했습니다.

2020-12-23 02:16 UTC, kst6294 commented on content/views.py
> +        services = ContentService.objects.get(name='watcha')
반영했습니다.

2020-12-23 02:19 UTC, kst6294 commented on \
> +import json
반영했습니다.

2020-12-23 11:23 UTC, soheon-lee commented on content/views.py
> +from content.models import ContentPeople, ContentGenre, ContentTag, Content, People, Genre, Tag, MovieOverview, ContentAvailableService, ContentService, ContentPhoto
생각보다 클래스가 엄청 많네요 ... 이렇게 길어지면 개별 라인으로 분리하시는 것이 좋겠습니닷!! 마지막 수정 !!

2020-12-23 11:28 UTC, kst6294 commented on content/views.py
> +from content.models import ContentPeople, ContentGenre, ContentTag, Content, People, Genre, Tag, MovieOverview, ContentAvailableService, ContentService, ContentPhoto
반영했습니다

2020-12-23 11:30 UTC, soheon-lee commented on content/urls.py
> +>>>>>>> main
급하셨군요 순태님
천천히 ~

2020-12-23 11:36 UTC, kst6294 commented on content/urls.py
> +>>>>>>> main
수정했습니다 ㅠㅠ

2020-12-23 11:55 UTC, merged