[15기 김순태] Add: 검색 API 구현 (title_korean / people_name) 검색
wecode-bootcamp-korea/15-1st-Youngchapedia-backend pull request #11
Opened 2020-12-22 04:52 UTC by kst6294

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 검색기능 추가
		 
## 수정 사항들 자세한 내용
- 쿼리스트링으로 keyword 를 받은 후, 1차로 title_korean 이 keyword 를 포함하는지 contains 를 통해 filter 후 결과에 추가.
- keyword 가 people_name 에 일치할 경우, 결과에 people_name 과 관련된 컨텐츠를 결과에 추가.

## 기타 질문 및 특이 사항
- 기능상에서 작동은 문제가 없으나, 예외처리를 하는 (타이틀은 있으나 사람이 없는 경우) 경우에 효율적 참고할 만한 내용..

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-22 13:31 UTC, lordmyshepherd requested changes

2020-12-22 13:31 UTC, lordmyshepherd commented on content/views.py
> +            )
128~138 코드와 140~150 코드가 중복되네요!
중복되지 않고 filtering할 수 있도록 구현해주세요~

2020-12-23 07:46 UTC, ulfrid commented on content/views.py
> +
from django.db.models import Q

ContentPeople.objects.filter(Q(content__title_korean__contains=) | Q(people__name__contains=))

2020-12-23 08:47 UTC, kst6294 commented on content/views.py
> +
갓...

2020-12-23 08:52 UTC, kst6294 commented on content/views.py
> +            )
반영했습니다.

2020-12-23 11:12 UTC, soheon-lee commented
LGTM!

2020-12-23 11:12 UTC, merged