[15기 이재혁] Add: review CRUD 기능
wecode-bootcamp-korea/15-1st-Youngchapedia-backend pull request #12
Opened 2020-12-22 06:00 UTC by leejaek

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 영화 리뷰 작성-조회-수정-삭제 기능 추가
- 영화 리뷰 좋아요 기능 추가
		 
## 수정 사항들 자세한 내용
- 영화 리뷰를 작성, 조회, 수정, 삭제  하는 API 구성
- 리뷰 조회 시, 남겨지 좋아요 횟수를 집계하여 함께 계산되도록 함
- 작성된 리뷰에 대해 좋아요를 남기고 삭제하는 API 구성

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-22 14:22 UTC, lordmyshepherd requested changes

2020-12-22 14:22 UTC, lordmyshepherd commented on review/views.py
> +            return JsonResponse({"message": "SUCCESS"}, status = 201)
리뷰 구현을 정말 잘 하셨네요 👍 
Django queryset API 중에 get_or_create()를 사용해서 구현해보시면 어떨까요??

2020-12-22 14:22 UTC, lordmyshepherd commented on review/views.py
> +                reviews = Review.objects.filter(content_id = content_pk)
여기서, `select_related`를 사용해보시면 어떨까요?

2020-12-22 14:22 UTC, lordmyshepherd commented on review/views.py
> +                    )
for문 보다 실행 속도가 빠른 `리스트 컴프리핸션`으로 수정해주세요!

2020-12-22 14:22 UTC, lordmyshepherd commented on review/views.py
> +                my_review = Review.objects.get(user = user, content_id = content_pk)
여기서도 `select_related`를 사용하시면 아래 `my_review_result` 데이터를 만들 때, db hit 횟수를 줄일 수 있을 것 같습니다!

2020-12-22 16:39 UTC, leejaek commented on review/views.py
> +            return JsonResponse({"message": "SUCCESS"}, status = 201)
넵 유사한 기능에 대해서 get_or_create를 사용해 수정했습니다.

2020-12-22 16:41 UTC, leejaek commented on review/views.py
> +                    )
해당 부분 기능을 별도의 class (`ContentReviewView`)로 분리해서 현재 삭제되었습니다.

2020-12-22 16:41 UTC, leejaek commented on review/views.py
> +                my_review = Review.objects.get(user = user, content_id = content_pk)
해당 부분 기능을 별도의 class (`ContentReviewView`)로 분리해서 현재 삭제되었습니다.

2020-12-22 16:46 UTC, leejaek commented on review/views.py
> +                reviews = Review.objects.filter(content_id = content_pk)
`my_review`를 가져오는 과정에서 user와 content를 select_related를 활용해서 가져올 수 있도록 수정했습니다.
(`reviews`는 해당 부분 기능을 별도의 class (ContentReviewView)로 분리해서 현재 삭제되었습니다.

2020-12-23 02:37 UTC, lordmyshepherd requested changes

2020-12-23 02:37 UTC, lordmyshepherd commented on review/views.py
> +                return JsonResponse({"message": "ALREADY_EXIST"}, status = 400)
한 사용자가 하나의 리뷰만 남길 수 있는게 맞나요?
그렇다면 고유한 user_id와 content_id만 조회하는게 좋을 것 같습니다. body 내용이 조금만 다르더라도 생성될 것 같습니다.
```suggestion
            review, created = Review.objects.get_or_create(user = user, content = content)
            if created:
                review.body = data['body']
                review.save()
            else:
                return JsonResponse({"message": "ALREADY_EXIST"}, status = 400)
```

2020-12-23 02:37 UTC, lordmyshepherd commented on review/views.py
> +                        }
👍

2020-12-23 02:37 UTC, lordmyshepherd commented on user/utils.py
> +            print(request.user)
프린트문은 지워주세요!

2020-12-23 02:37 UTC, lordmyshepherd commented on review/views.py
> +                reviews  = Review.objects.select_related('user').prefetch_related('user__rated_contents', 'liked_users', 'user__archived_contents').filter(content = content_pk)
불필요하게 많은 table을 한번에 조회하는 것 같아요!
view에서 사용할 테이블만 join해서 가져오는게 좋을 것 같습니다!

2020-12-23 02:37 UTC, lordmyshepherd commented on review/views.py
> +                    likes = ReviewLike.objects.filter(review_id = review.id).count()
이 부분을 아래 dictionary를 생성하는 부분에 합쳐볼 수 있을 것 같습니다!
review에서 rating에 접근해서 데이터를 불러오고, review에서 archive에서 접근해서 데이터를 불러올 수 있도록 수정해주세요.

2020-12-23 07:12 UTC, leejaek commented on review/views.py
> +                    likes = ReviewLike.objects.filter(review_id = review.id).count()
넵 딕셔너리 내로 넣어서 한꺼번에 list comprehension으로 처리될 수 있도록 변경하였습니다.

2020-12-23 07:12 UTC, leejaek commented on review/views.py
> +                reviews  = Review.objects.select_related('user').prefetch_related('user__rated_contents', 'liked_users', 'user__archived_contents').filter(content = content_pk)
넵 수정했습니다.

2020-12-23 07:12 UTC, leejaek commented on user/utils.py
> +            print(request.user)
네!

2020-12-23 07:12 UTC, leejaek commented on review/views.py
> +                return JsonResponse({"message": "ALREADY_EXIST"}, status = 400)
네 말씀하신 방법으로 수정했습니다.

2020-12-23 07:16 UTC, soheon-lee commented on review/views.py
> +                return JsonResponse({"message": "ALREADY_EXIST"}, status = 400)
`else`가 없어도 바로 위의 `if`문이 만족되지 않는다면 바로 도달할 수 있는 로직입니다. 꼭 필요한 경우가 아니면 `else`를 사용하지 않는 것이 보다 파이썬다운 코딩 스타일입니다. `else`는  지워주셔도 됩니다 :)

2020-12-23 07:16 UTC, soheon-lee commented on review/views.py
> +                return JsonResponse({"message": "INVALID_CONTENT_ID"}, status = 400)
마찬가지로! `else`가 없어도 바로 위의 `if`문이 만족되지 않는다면 바로 도달할 수 있는 로직입니다. 꼭 필요한 경우가 아니면 `else`를 사용하지 않는 것이 보다 파이썬다운 코딩 스타일입니다. `else`는  지워주셔도 됩니다 :)

2020-12-23 07:24 UTC, leejaek commented on review/views.py
> +                return JsonResponse({"message": "ALREADY_EXIST"}, status = 400)
수정 완료했습니다.

2020-12-23 07:24 UTC, leejaek commented on review/views.py
> +                return JsonResponse({"message": "INVALID_CONTENT_ID"}, status = 400)
수정 완료했습니다.

2020-12-23 11:15 UTC, soheon-lee commented on review/views.py
> +                                "likes"        : ReviewLike.objects.filter(review_id = review.id).count()
`reviewlike_set`도 미리 캐싱해와서 바로 review.reviewlike_set.count()로 바로 쓰면 어떨까요?

2020-12-23 14:42 UTC, lordmyshepherd approved these changes

2020-12-23 14:42 UTC, lordmyshepherd commented
LGTM 👍

2020-12-23 14:42 UTC, merged