[15기 이재혁] Modify: 영화별 평균 rating 연산 기능 함수화
wecode-bootcamp-korea/15-1st-Youngchapedia-backend pull request #14
Opened 2020-12-22 12:08 UTC by leejaek

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 영화별 평균 별점 연산 기능 함수화
		 
## 수정 사항들 자세한 내용
- 영화별 평균 별점 연산 기능이 다양한 view에서 필요하다고 판단되어 별도의 함수(`ratings_calc`)로 분리

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-22 14:47 UTC, lordmyshepherd requested changes

2020-12-22 14:47 UTC, lordmyshepherd commented on archive/utils.py
> +def ratings_calc(content_pk):
함수는 동사로 시작해주세요~
```suggestion
def calculate_ratings(content_pk):
```

2020-12-22 14:47 UTC, lordmyshepherd commented on archive/utils.py
> +    return average_rating
한 줄로 줄여주세요~

2020-12-22 16:53 UTC, leejaek commented on archive/utils.py
> +def ratings_calc(content_pk):
수정 완료했습니다.

2020-12-22 16:53 UTC, leejaek commented on archive/utils.py
> +    return average_rating
수정 완료했습니다.

2020-12-23 02:39 UTC, lordmyshepherd approved these changes

2020-12-23 02:39 UTC, lordmyshepherd commented on archive/views.py
> +        watch = Archive.objects.filter(user = user, archive_type_id = 2).count()
2차 프로젝트 에서는 annotate()를 공부해서 적용해보세요~

2020-12-23 02:39 UTC, lordmyshepherd commented
LGTM 👍

2020-12-23 02:39 UTC, merged