#1 people api complete
wecode-bootcamp-korea/15-1st-Youngchapedia-backend pull request #5
Opened 2020-12-17 16:36 UTC by kst6294

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- PEOPLE API 구현 : 아래 이미지와 같이 특정한 사람 (배우, 감독 등) 의 기본정보 및 참여한 컨텐츠 목록을 포함
![image](https://user-images.githubusercontent.com/44313290/102514616-09fec980-40d0-11eb-93be-afafde0e4a47.png)
- 데이터베이스에 중복된 데이터가 있을 경우, 중복을 제외한 데이터만 저장
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Many to Many 관계 데이터 저장 시, 중복 데이터를 제외하는 코드를 작성
-- 리스트에 담은 job_list 의 경우 set 으로 형변환을 통해 중복값 제거 후 다시 list 형 변환.
-- 리스트 안에 딕셔너리의 형태로 저장되는 content_list 의 경우, 튜플로 형 변환 후, 다시 딕셔너리의 형태로 형 변환 (구글 검색을 통해 문제 해결, 구조를 정확히 이해는 하지 못함)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 
- 데이터베이스에 중복된 데이터가 저장되어 있을 경우, 중복을 제외하고 출력하는 방식으로 하나요? 아니면 데이터 베이스에 불필요한 중복 데이터를 삭제 하나요?
- 정참조, 역참조 테이블의 데이터에 접근하는 더 효율적인 방법이 궁금합니다. (select_related 등) 어디서 참고 하면 좋을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-18 01:22 UTC, jamessoun93 commented
충돌해결해주세요~

2020-12-18 03:14 UTC, kst6294 commented
> 충돌해결해주세요~

해결했습니다.

2020-12-18 05:08 UTC, jamessoun93 requested changes

2020-12-18 05:08 UTC, jamessoun93 commented on content/views.py
> +            job_list     = list(set([job.job.name for job in jobs]))
중복을 제거해주기 위해 `set`으로 감싸주셨는데, 자료구조의 특성을 아주 잘 이해하고 계신것 같아서 기분이 좋네요 순태님 👍
하지만 여기서는 전부 가져와서 파이썬으로 중복을 걸러주기보다 데이터베이스 쿼리를 날릴때부터 중복값을 거른 결과물을 가져오시는게 좋습니다. 

hint: `distinct()` 를 사용해보세요.

2020-12-18 05:08 UTC, jamessoun93 commented on content/views.py
> +                )
`content_list` 에는 `dictionary` 들이 모여있어서 `if` 문에 있는 조건은 여기서는 별 의미가 없어보이는데 어떤 의도로 작성해주신건가요?

2020-12-18 05:08 UTC, jamessoun93 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
`list comprehension` 의 장점은 가독성인데 이렇게 사용하시면 가독성이 굉장히 떨어집니다. 
지금 중복 제거 로직이 여러개가 겹쳐있는데 위에 남겨드린 코멘트 내용대로 수정해보시고 여기도 고민해보세요.

2020-12-18 05:14 UTC, kst6294 commented on content/views.py
> +            job_list     = list(set([job.job.name for job in jobs]))
확인해보겠습니다! 감사합니다.

2020-12-18 05:17 UTC, jamessoun93 commented
그리고 `.DS_Store` 파일은 없애주세요.

2020-12-18 05:18 UTC, kst6294 commented on content/views.py
> +                )
데이터 중복을 체크해보고자 시도한 방법중 하나 였습니다. 다만 의미가 없는 조건인것을 저도 확인 후에 삭제 하였는데, 
다른 코드들도 삭제돼서 되돌리기를 하던 중 코드가 다시 생성되었고, 다시  삭제하는 것을 빼먹어서 해당 코드가 포함되어 있습니다. 
삭제 하겠습니다!

2020-12-18 05:18 UTC, kst6294 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
넵 확인해보겠습니다.

2020-12-18 08:47 UTC, kst6294 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
해당 부분에 피드백 주셨던 distinct() 는 MySql에서 정상적으로 작동하지 않는 문제가 있어, 코드 수정 진행하지 않았습니다.

2020-12-18 08:48 UTC, kst6294 commented on content/views.py
> +            job_list     = list(set([job.job.name for job in jobs]))
해당 부분 도 동일하게 distinct() 가 MySql에서 정상적으로 작동하지 않는 문제가 있어, 코드 수정 진행하지 않았습니다.

2020-12-20 14:35 UTC, jamessoun93 requested changes

2020-12-20 14:35 UTC, jamessoun93 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
이 부분은 `distinct()` 와 관계없이 `list comprehension` 을 복잡하게 사용하신 경우라서 이 부분은 한번 고민해보시고 수정해주세요.

2020-12-20 14:35 UTC, jamessoun93 commented on content/views.py
> +            return JsonResponse({'ERROR' : 'PEOPLE_ERROR'}, status=400)
client 쪽에서 에러메세지만 보고 어떤 에러인지 정확하게 알기가 힘들 수 있습니다. 조금 더 명확한 에러 메세지로 변경해주세요.

2020-12-20 14:35 UTC, jamessoun93 commented on content/views.py
> +            return JsonResponse({'ERROR' : e}, status=400)
이런식으로 모든 에러를 한번에 잡아서 e 로 메세지를 뿌려주는 방식은 좋지 않습니다. 여러가지 시도를 통해 날 수 있는 에러를 직접 찾아 하나하나 명확하게 잡아주시는게 더욱 더 효율적인 에러 핸들링 방법입니다.

2020-12-20 14:35 UTC, jamessoun93 commented on content/views.py
> +            return JsonResponse({'ERROR' : e}, stauts=400)
위 리뷰 내용과 같습니다.

2020-12-20 14:35 UTC, jamessoun93 commented on content/views.py
> +            return JsonResponse({'ERROR' : e}, status=400)
위 리뷰 내용과 같습니다.

2020-12-20 14:35 UTC, jamessoun93 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
위 리뷰 내용과 같습니다.

2020-12-20 14:35 UTC, jamessoun93 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
위 리뷰 내용과 같습니다.

2020-12-20 14:35 UTC, jamessoun93 commented on content/views.py
> +
이런 코드는 따로 저장해두셨다가 완성이 되면 `git` 에 `push` 해주세요.

2020-12-21 03:29 UTC, kst6294 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
list comprehension 에서 for loop 형식으로 수정했습니다.
for 방식이어서 list comprehension 을 복잡하게 사용한 것 보단 가독성이 높아진 것 같습니다.

2020-12-21 03:29 UTC, kst6294 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
수정사항 반영 했습니다.

2020-12-21 03:29 UTC, kst6294 commented on content/views.py
> +            return JsonResponse({'ERROR' : e}, status=400)
수정사항 반영 했습니다.

2020-12-21 03:29 UTC, kst6294 commented on content/views.py
> +            return JsonResponse({'ERROR' : e}, stauts=400)
수정사항 반영 했습니다.

2020-12-21 03:30 UTC, kst6294 commented on content/views.py
> +            return JsonResponse({'ERROR' : e}, status=400)
Model.DoesNotExist 외 에러가 발생하지 않아서, 해당 에러 코드 외에는 삭제했습니다.

2020-12-21 03:31 UTC, kst6294 commented on content/views.py
> +            return JsonResponse({'ERROR' : 'PEOPLE_ERROR'}, status=400)
재혁님과 소통하여 에러메시지 양식을 통일했습니다.

2020-12-21 03:45 UTC, kst6294 commented on content/views.py
> +
반영했습니다.

2020-12-21 03:45 UTC, kst6294 commented on content/views.py
> +            content_list = [dict(new_content) for new_content in {tuple(content.items()) for content in content_list}]
수정사항 반영 했습니다.

2020-12-21 04:35 UTC, jamessoun93 requested changes

2020-12-21 04:35 UTC, jamessoun93 commented on content/views.py
> +                content_list = dict(tuple(content.items()))
순태님 이 부분에서 어떤걸 처리하고 싶으신건지 조금 헷갈려서 코멘트 남깁니다. 답글로 설명해주세요.

2020-12-21 04:35 UTC, jamessoun93 commented on user/views.py
> +            return JsonResponse({'MESSAGE' : 'ERROR'}, status = 400)
아직 미완성인 코드처럼 보이는데, 아직 추가구현중이시면 `추가 기능 구현중` 라벨로 변경해주세요.

2020-12-21 04:38 UTC, kst6294 commented on user/views.py
> +            return JsonResponse({'MESSAGE' : 'ERROR'}, status = 400)
이 코드는 user 앱의 새로운 기능을 구현중이었는데, content에 들어간 듯 합니다. 제외하고 commit 하겠습니다.

2020-12-21 06:33 UTC, kst6294 commented on content/views.py
> +                content_list = dict(tuple(content.items()))
코드 작성 초반에 PK제외한 모든 데이터들이 동일한 경우가 있었고, 해당 데이터 API 를 전달할 때, 중복된 데이터를 제외하고자 해당 코드를 작성했습니다.

그런데 데이터베이스 자체에 중복된 데이터(PK를 제외한 모든 데이터들가 동일한 경우)가 존재하지 않기 때문에 불필요한 코드라고 생각되어 삭제했습니다.

2020-12-21 06:34 UTC, kst6294 commented on content/views.py
> +                content_list = dict(tuple(content.items()))
초반에 데이터베이스에 테스트용으로 넣어놓은 중복된 데이터들을 처리하고자 작성한 코드였습니다.

2020-12-21 13:23 UTC, jamessoun93 commented on content/views.py
> +                content_list = dict(tuple(content.items()))
말씀하신 내용은 중복된 데이터를 제외하고자 하는 목적이 있으신데, 
`content_list = dict(tuple(content.items()))` <- 이 코드의 결과물이 무엇일거라고 생각하시고 작성하셨는지 그리고 결과값을 확인 해보셨는지 궁금합니다.

2020-12-21 13:58 UTC, kst6294 commented on content/views.py
> +                content_list = dict(tuple(content.items()))
처음 의도는 복잡한 list comprehension 을 변경하고 api 를 response 할 때 중복값을 제외하고자 했습니다.

결과물이라고 하심은 어떻게 작동이 될 것인지 제가 생각한 과정을 말씀하시는 것인지요? 
제가 예상한 것은 dictionary 를 tuple로 형변환을 하면 자동적으로 중복되는 데이터가 제외되고, 다시 dict 로 형변환을 하면 제가 원하는 dictionary 형태의 중복값이 제외한 api로 바꿔지는 것이었습니다. 

dictionary 때와 tuple 로 변경되고, 다시 dictionary 일 때 각각 print 를 찍어보고 서버를 가동 했을 때 에러가 없어서 정상적으로 동작했다고 생각했지만, 애초에 중복된 데이터가 없어서 정상적으로 작동된 것으로 생각됩니다.

2020-12-21 14:28 UTC, jamessoun93 approved these changes
LGTM

2020-12-21 14:28 UTC, merged