[15기 이재혁] Add: User 영화 Archive (보고싶어요, 보는중, 관심없어요) 기능
wecode-bootcamp-korea/15-1st-Youngchapedia-backend pull request #9
Opened 2020-12-21 01:34 UTC by leejaek

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- Archive 기능 추가
		 
## 수정 사항들 자세한 내용
- 유저가 영화에 대해 '보고싶어요', '보는 중', '관심없어요' 중 하나를 선택하면 서버로 전송되어 저장되도록 함
- 영화 별점 조회 시 로그인한 유저의 영화별점, 해당 영화의 전체 영화 별점 조회 기능을 추가

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-21 04:07 UTC, soheon-lee commented on archive/views.py
> +            rating  = Rating.objects.get(user = user, content = content)
위 36번줄, 37번줄에서 user와 content를 가져왔기 때문에, 두 객체를 이용하면 Rating클래스에 직접 접근하지 않고도 ,해당 유저에 연결된 rating 데이터를 불러올 수 있습니다. :) user의 속성으로 연결된 rating데이터를 찾아오는 방법을 활용해보세요.

그 이유는 Class 하나 하나에 접근할 때마다 django는 database에 mysql query를 날리게 됩니다. 이 하나하나의 query가 리소스이기 때문에, 최대한 줄이는 방향으로 로직을 작성하시는 것이 좋습니다.

2020-12-21 04:07 UTC, soheon-lee commented on archive/views.py
> +                return JsonResponse({"message": "ALREADY_EXIST"}, status = 400)
여기에서도 89번째 줄에서 user를 지칭하였으므로, 그 user에 연결된 archive 데이터 가운데 content가 저 90번째 변수인 것을 필터링 하는 방법을 추천드립니다. 바로 위 리뷰와 같은 이유입니다. :)

2020-12-21 04:07 UTC, soheon-lee commented on archive/views.py
> +            return JsonResponse({"message": "UNVALID_ARCHIVETYPE"}, status = 400)
patch goood!

2020-12-21 04:07 UTC, soheon-lee commented on archive/views.py
> +            ratings = Rating.objects.filter(content = content)
rating도 Rating객체에 따로 접근해서 SELECT query를 날리기 보다는 이미 가져온 158 번째 줄 content 변수에서 이어진 속성으로 접근해오시는 방법을 시도해보세요 :)

2020-12-21 04:07 UTC, soheon-lee commented on archive/views.py
> +                )
good!
results를 선언하는 방법을 `list comprehension`으로 한 번 바꿔보세요, 일반 for loop보다 2배 가량 빠르게 동작합니다

2020-12-21 04:07 UTC, soheon-lee commented on archive/views.py
> +                )
아래 다른 for loop들도 변경해보세요 :)

2020-12-21 04:37 UTC, jamessoun93 commented on archive/views.py
> +            rating  = Rating.objects.get(user = user, content = content)
이 부분은 지난 번 PR 에서 리뷰남겨드린걸로 알고있는데, 반영되기 전 코드로 그대로 다시 올라왔네요. 어떤 상황인지 설명해주세요.
https://github.com/wecode-bootcamp-korea/15-1st-Youngchapedia-backend/pull/8#discussion_r545581702

2020-12-21 05:21 UTC, leejaek commented on archive/views.py
> +            rating  = Rating.objects.get(user = user, content = content)
@jamessoun93 넵 지난번 리뷰에서 수정했던 부분은 '해당 영화의 전체 rating을 조회하는 기능'이었는데,  해당 기능을 아래쪽 `ContentRatingView` class로 분리해서 당시 수정했던 코드는 아래쪽에 기재되어있습니다!
현재 소헌님이 리뷰해주신 GET 함수는 '로그인한 유저가 해당 영화에 평가한 rating을 조회하는 기능'으로 새로 작성했는데, 지난번에 정정받은 방식이 아닌 기존 방식으로 작성되어서 코멘트 주신 방법으로 재수정하겠습니다.

2020-12-21 08:34 UTC, leejaek commented on archive/views.py
> +                )
넵 위 loop 포함해서 list comprehension으로 변경했습니다!

2020-12-21 08:34 UTC, leejaek commented on archive/views.py
> +            rating  = Rating.objects.get(user = user, content = content)
user를 활용해 접근하는 방식으로 수정했습니다.

2020-12-21 08:36 UTC, leejaek commented on archive/views.py
> +                return JsonResponse({"message": "ALREADY_EXIST"}, status = 400)
넵 user를 활용해 역참조로 접근하는 방식으로 수정했습니다.

2020-12-21 08:37 UTC, leejaek commented on archive/views.py
> +            ratings = Rating.objects.filter(content = content)
넵 content를 통해 참조해 오는 방식으로 수정했습니다.

2020-12-21 13:27 UTC, jamessoun93 commented on archive/views.py
> +            rating  = Rating.objects.get(user = user, content = content)
확인했습니다.

2020-12-21 13:30 UTC, jamessoun93 requested changes

2020-12-21 13:30 UTC, jamessoun93 commented on archive/models.py
> +    user         = models.ForeignKey(User, on_delete=models.CASCADE, related_name='archived_movie')
related_name 사용 잘하셨습니다. 하지만 조금 더 알기 쉽게 복수형으로 지어주시는게 좋을 것 같습니다. views.py 에서 봤을때 foreign key 인줄 알았네요.

2020-12-21 13:30 UTC, jamessoun93 commented on archive/views.py
> +            if user.archived_movie.filter(content_id = content_pk).exists():
이 부분입니다.

2020-12-22 05:45 UTC, jamessoun93 approved these changes
LGTM 👍

2020-12-22 05:46 UTC, merged